### ISSUE TITLE
Automatically disable the plugin's features if it's running a vulnerable version

### ISSUE THREAD

**Issue by lMartin3** [lMartin3/BetterShulkerBoxesRewritten#11]
Description: add an option (enabled by default) to let the plugin check if its running a vulnerable version. The list will be placed in a file in the github repo like the  changelog.

**Comment by Hutch79** [comment]
Ohh, that sounds nice!
But do I understand that right? It automatically disables the Plugin if there is something like a duplication bug in it?
This would be awesome!!!

**Comment by lMartin3** [comment]
Sorry for the late reply, this feature works just as you described, and it is already implemented in the latest version
