### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by Hutch79** [lMartin3/BetterShulkerBoxesRewritten#2]
Steps to duplicate all content of a shulkerbox:
1. Open a shulkerbox with Rightklicking
2. Move all items from the shulkerbox to your Inventory or drop it
3. Right-click the Open shulkerbox in your Inventory, without closing it

**Comment by lMartin3** [comment]
Thank you for reporting the issue! Version 3.1.1 should no longer have this issue, you can download it [here](https://github.com/lMartin3/BetterShulkerBoxesRewritten/releases/tag/3.1.1) or on [Spigot](https://www.spigotmc.org/resources/bsb-better-shulker-boxes-1-13-1-18.58837/).

**Comment by Hutch79** [comment]
Wow, that was fast!
Thanks for fixing!
