### ISSUE TITLE
Feature request - Chestsort

### ISSUE THREAD

**Issue by resi23** [lMartin3/BetterShulkerBoxesRewritten#20]
Hello, I like the chestsort hotkeys is it possible to make BSB compatible with chestsort? (https://www.spigotmc.org/resources/chestsort-api.59773/)

**Comment by lMartin3** [comment]
Fixed by https://github.com/lMartin3/BetterShulkerBoxesRewritten/commit/04eab1225565bbfaf7df0740bf0b5529dab7adde
