### ISSUE TITLE
Add hex code support to config.yml

### ISSUE THREAD

**Issue by PolsatGraniePL** [lMartin3/BetterShulkerBoxesRewritten#21]
![image](https://user-images.githubusercontent.com/88681446/173637250-7c2a1fba-fd9a-406f-8251-9128140ff78b.png)

**Comment by lMartin3** [comment]
Added support for hex, gradients and more (https://github.com/lMartin3/BetterShulkerBoxesRewritten/commit/f4e3ec1ceaafb5576f771a87c025023a04caf414)

**Comment by lMartin3** [comment]
Documentation for feature pending
