### ISSUE TITLE
Please add 1.19 support

### ISSUE THREAD

**Issue by Animationking11** [lMartin3/BetterShulkerBoxesRewritten#22]
Please I need it for my server

**Comment by Hutch79** [comment]
I quickly tested the Plugin on a 1.19 Server and I had no problems or error messages in the console.
I haven't tested everything tough.

If you find anything that does not work, you can write it in this issue.

**Comment by Qiasfah** [comment]
It works, but there's something wrong with how it's handling closing of the interface after opening a box.

Operation:
-Open Inventory
-Right click on shukler box
-Close inventory
-Open Inventory again (NOTICE: Cursor acts as if it's dragging the previously opened box, and won't update till you click something)
![2022-07-17 13-54-28](https://user-images.githubusercontent.com/15950877/179420772-ad697ee7-c4e9-4478-a138-60bb40bccffa.gif)

**Comment by resi23** [comment]
I think this problem is as old as the plugin itself. It also only happens when you open the shulker with a right click in the inventory. If you have the Shulker in your hand and right-click it in the air and it opens, this problem does not occur.

**Comment by resi23** [comment]
If you build it yourself here is a workaround for Shulker box caught in cursor after opening with right click in inventory. However, it does not solve the problem that the inventory is not updated
https://github.com/lMartin3/BetterShulkerBoxesRewritten/pull/26/commits/a62815493b7a6b12d3fb9da4fef9840441d86d37

**Comment by lMartin3** [comment]
Fixed by #27
