### ISSUE TITLE
Feature request - World guard 

### ISSUE THREAD

**Issue by lMartin3** [lMartin3/BetterShulkerBoxesRewritten#3]
Description: Add world guard region support, and a configuration option to allow using the plugin only on certain regions, or otherwise, using the plugin anywhere but in those regions.
Suggested by: Halvnaken#5585

**Comment by KaspianDev** [comment]
prs needed?

**Comment by lMartin3** [comment]
It'd be appreciated

**Comment by KaspianDev** [comment]
Looks like their api requires java 17 to be used, what do we do in that scenario?
