### ISSUE TITLE
Feature request - Back to backpack page

### ISSUE THREAD

**Issue by ApliNi** [lMartin3/BetterShulkerBoxesRewritten#34]
I would like to be able to show the backpack page after the player closes the shulker box, rather than just exiting.
This will be handy for players who are looking for items.

Edit: Or can continue to open other shulker boxes in the interface of opening the shulker box.

**Comment by lMartin3** [comment]
Sorry, what do you mean by "backpack page"? Making players able to open a shulker from the interface is possible though

**Comment by ApliNi** [comment]
> Sorry, what do you mean by "backpack page"? Making players able to open a shulker from the interface is possible though

Press E and right-click on the shulker box, which looks like this

**Comment by lMartin3** [comment]
Sorry but player inventories are completely clientside, plugins cannot make a player open their inventory

**Comment by ApliNi** [comment]
can continue to open other shulker boxes in the interface of opening the shulker box. 
how about this?

**Comment by lMartin3** [comment]
yep, I'll add that

**Comment by lMartin3** [comment]
Added! Will be released in `4.1.0`

**Comment by lMartin3** [comment]
Done! You can download it via [SpigotMC ](https://www.spigotmc.org/resources/bsb-better-shulker-boxes-1-13-1-19-2.58837/)or on the releases page

**Comment by ApliNi** [comment]
Do you think it is possible to open the shulker box in the box? 
![image](https://user-images.githubusercontent.com/59365724/189534290-60cc34ce-6afd-4ea7-b560-21d1e74d6325.png)
