### ISSUE TITLE
New feature - Automatic updates

### ISSUE THREAD

**Issue by lMartin3** [lMartin3/BetterShulkerBoxesRewritten#4]
Allow the plugin to update itself, downloading the latest JAR from GitHub. This option should be disabled by default, and users should be able to execute the command /bsb update to download the update.

**Comment by lMartin3** [comment]
Edit on the scope of this feature: the plugin will not update itself but rather the administrators will run `/bsb update` to update it.

**Comment by Hutch79** [comment]
I would recommend an option in the config for auto update.
Maybe also an option like `auto-update-on-vulnerability` so an auto update only happens if the current version is vulnerable

**Comment by lMartin3** [comment]
Thinking about it, I believe BSB is ok without auto-updating. It could introduce vulnerabilities and from a server admin perspective I wouldn't like my plugins to be able to update themselves. If a version with malware in it was published it'd be a disaster.

I'll leave this on hold for now
