### ISSUE TITLE
[Enhancement] Shulker Enchantments

### ISSUE THREAD

**Issue by LadyHaley** [lMartin3/BetterShulkerBoxesRewritten#41]
Posted here as directed on spigot

xisuma made a video about inventoty issues and solutions, in it he outlined an idea to have an enchantment for shulkers that make them even more useful.

Blocks don't however keep NBT data for enchantments, I suspect that to be the same for shulkers, so maybe an item that you put inside them could give them the ability he mentioned in his video on it

[https://youtu.be/zJtJ90Vl03M](url)

**Comment by Hutch79** [comment]
Hey @LadyHaley 

May you write the suggestion out?
A 19 Minutes Video is quite long to watch just for one suggestion.

What kind of Enchantment would you like to have added?
What should it do?

This Information would make it much easier to understand what you wish to be added and if it's possible or if it needs another way.

**Comment by Folas1337** [comment]
The suggestions start right here: https://youtu.be/zJtJ90Vl03M?t=491

To me sounds way out of scope for the plugin and what it's supposed to do. My personal advice: Don't do it, it's like asking for trouble cause you can't properly support it and the code would probably end up very hacky.

**Comment by Hutch79** [comment]
I need to agree with @Folas1337 here.

The Enchantemends are way out of the "open a shulker in your hand or inv" scope.

I already know a Plugin doing one of the things, maybe it'l be something for you @LadyHaley ?
https://www.spigotmc.org/resources/autoshulker.89807/

**Comment by Hutch79** [comment]
Closing since no answer from requester.
Just reopen it if you want to add something here.
