### ISSUE TITLE
When a new version is released, the Spigot forums API will still return the old version number

### ISSUE THREAD

**Issue by lMartin3** [lMartin3/BetterShulkerBoxesRewritten#5]
When a user updates the plugin to a version that has been published not long ago, Spigot will still return the old version number, making the plugin think it is outdated. The updater needs to take this into account, trying to figure out if the current version is newer or not.

**Comment by Hutch79** [comment]
Maybe [spiget](https://spiget.org/) is faster?

**Comment by lMartin3** [comment]
I could use spiget, but I believe I'll stick to Spigot's official API and implement some sort of regex check to see if the current version is newer
